version: '3.8'
services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: url-shortener-dynamodb
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    ports:
      - "8000:8000"
    working_dir: /home/dynamodblocal

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    container_name: dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: http://dynamodb-local:8000
    depends_on:
      - dynamodb-local

  minio:
    image: minio/minio:latest
    container_name: url-shortener-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # endpoint S3
      - "9001:9001"   # console web
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
